### ISSUE TITLE
What return this method?

### ISSUE THREAD

**Issue by Radzhab** [markmeeus/ASHWIDParser#1]
What its display to me?
![image](https://cloud.githubusercontent.com/assets/2556411/12872046/ec267990-cda6-11e5-93ef-45c16e74d5f0.png)

**Comment by markmeeus** [comment]
It gives you the 2 bytes of the app-specific hardware id basedon the network adapter.

**Comment by Radzhab** [comment]
how decrypt this two bytes? 201 and 4. Whats it meaning? Network adapter firmware, id or other?

**Comment by markmeeus** [comment]
The data means nothing, it's a value that represents a hardware component but it's unique for your app.
Another app will get another value in the same hardware, and you app will get another value on other hardware.

This package just parses the result from, so it's easier to use specific components:

``` c#
HardwareIdentification.GetPackageSpecificToken();
```

Make sure you understand this:
https://msdn.microsoft.com/EN-US/library/windows/apps/jj553431.aspx
