### ISSUE TITLE
How generate unique ASHWID?

### ISSUE THREAD

**Issue by Radzhab** [markmeeus/ASHWIDParser#2]
How generate unique ASHWID?

**Comment by markmeeus** [comment]
If you just need an app specific hardware id, all you need to do is call this method:

``` c#
var ashwid = HardwareIdentification.GetPackageSpecificToken(null).Id.ToArray();
```

It gives you a byte[], if you wish to have it as a string:

``` c#
var ashwidAsString = System.Text.Encoding.Default.GetString(ashwid);
```

What this package does is parse the byte[] and split it into the separate components per component type.
This can be handy if you want to base you id on just a few hardware components.

Let's say you only want Process and SystemBios: (So the user can change his disk and it won't affect your ashwid)

``` c#
var idData = HardwareIdentification.GetPackageSpecificToken(null).Id.ToArray();
var components = ASHWIDParser.ParseBytes(idData);

return string.Join(",", 

  components

  .Where(
    (component) => component.Type == ASHWIDParser.ASHWIDComponentType.Processor                            
                || component.Type == ASHWIDParser.ASHWIDComponentType.SystemBIOS)

  .OrderBy((component) => component.Type).

  .Select((component) => System.Text.Encoding.Default.GetString(component.Value)

).ToArray());
```

More info:
https://msdn.microsoft.com/EN-US/library/windows/apps/jj553431.aspx
